# Generated by Django 3.2.5 on 2021-08-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tqyeem_app', '0002_approvedseller_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.IntegerField(unique=True),
        ),
    ]
